// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateYouTube() {
  return window['go']['main']['App']['AuthenticateYouTube']();
}

export function HasYouTubeToken() {
  return window['go']['main']['App']['HasYouTubeToken']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenVideoFileDialog() {
  return window['go']['main']['App']['OpenVideoFileDialog']();
}

export function RunDryTest(arg1) {
  return window['go']['main']['App']['RunDryTest'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartUpload(arg1, arg2) {
  return window['go']['main']['App']['StartUpload'](arg1, arg2);
}
