// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';

export function AuthenticateYouTube():Promise<void>;

export function HasYouTubeToken():Promise<boolean>;

export function LoadConfig():Promise<config.Config>;

export function OpenVideoFileDialog():Promise<string>;

export function RunDryTest(arg1:string):Promise<main.UploadResult>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function StartUpload(arg1:string,arg2:main.SermonMeta):Promise<main.UploadResult>;
